# Generated by Django 2.2 on 2021-06-19 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapuserrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
