# Generated by Django 2.2 on 2021-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210619_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapuserrestaurant',
            name='suggested',
            field=models.BooleanField(default=True),
        ),
    ]
